osx_m1_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  install_deps_script: |
    brew install autoconf automake libtool coreutils # coreutils is to get gtimeout for CI and is not universally required by qthreads.
    brew install hwloc
    hwloc-ls --version
  build_script: |
    ./autogen.sh
    ./configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    gtimeout --foreground 8m make check

freebsd_task:
  freebsd_instance:
    image_family: freebsd-13-2
  install_deps_script: |
    pkg install -y bash
    pkg install -y llvm autoconf automake libtool
    pkg install -y hwloc
  build_script: |
    bash autogen.sh
    bash configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    timeout --foreground 8m make check

# arm_linux_task:

# linux_musl_task:

