osx_m1_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  install_deps_script: |
    brew install autoconf automake libtool coreutils # coreutils is to get gtimeout for CI and is not universally required by qthreads.
    brew install hwloc
    hwloc-ls --version
  build_script: |
    ./autogen.sh
    ./configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    gtimeout --foreground 8m make check

# freebsd_task:

# arm_linux_task:

