osx_m1_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  install_deps_script: |
    brew install autoconf automake libtool coreutils # coreutils is to get gtimeout for CI and is not universally required by qthreads.
    brew install hwloc
    hwloc-ls --version
  build_script: |
    ./autogen.sh
    ./configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    gtimeout --foreground 3m make check

freebsd_task:
  freebsd_instance:
    image_family: freebsd-13-2
  install_deps_script: |
    pkg install -y bash
    pkg install -y llvm autoconf automake libtool
    pkg install -y hwloc
  build_script: |
    bash autogen.sh
    bash configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    timeout --foreground 2m make check

arm_linux_task:
  arm_container:
    image: gcc:latest
  install_deps_script: |
    apt-get update -y
    apt-get install -y autoconf automake libtool
    apt-get install -y hwloc
  build_script: |
    ./autogen.sh
    ./configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    timeout --foreground 2m make check

arm_linux_clang_task:
  arm_container:
    image: gcc:latest
  env:
    CC: clang
    CXX: clang++
  install_deps_script: |
    apt-get update -y
    apt-get install -y software-properties-common
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    apt-add-repository 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main'
    apt-get install -y clang
    apt-get install -y autoconf automake libtool
    apt-get install -y hwloc
  build_script: |
    ./autogen.sh
    ./configure --enable-picky
    make -j$CIRRUS_CPU
  test_script: |
    timeout --foreground 2m make check

